package com.example.tictacjournalofficial.quotes;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class QuotesData {
    public static List<QuotesList> getLifeQuotes() {
        final List<QuotesList> lifeQuotesList = new ArrayList<>();

        QuotesList q1 = new QuotesList("I am the master of my mind. I am the captain of my soul.", "- Anonymous");
        lifeQuotesList.add(q1);
        QuotesList q2 = new QuotesList("Hey you, everything's gonna be alright. ;)", "- Topitops");
        lifeQuotesList.add(q2);
        QuotesList q3 = new QuotesList("Keep going and never give up!", "- Your future self.");
        lifeQuotesList.add(q3);
        QuotesList q4 = new QuotesList("Success is not final, failure is not fatal: It is the courage to continue that counts.", "- Winston Churchill");
        lifeQuotesList.add(q4);
        QuotesList q5 = new QuotesList("Believe you can and you're halfway there.", "- Theodore Roosevelt");
        lifeQuotesList.add(q5);
        QuotesList q6 = new QuotesList("The only limit to our realization of tomorrow will be our doubts of today.", "- Franklin D. Roosevelt");
        lifeQuotesList.add(q6);
        QuotesList q7 = new QuotesList("Your time is limited, don't waste it living someone else's life.", "- Steve Jobs");
        lifeQuotesList.add(q7);
        QuotesList q8 = new QuotesList("The future belongs to those who believe in the beauty of their dreams.", "- Eleanor Roosevelt");
        lifeQuotesList.add(q8);
        QuotesList q9 = new QuotesList("The best way to predict your future is to create it.", "- Peter Drucker");
        lifeQuotesList.add(q9);
        QuotesList q10 = new QuotesList("The only way to do great work is to love what you do.", "- Steve Jobs");
        lifeQuotesList.add(q10);
        QuotesList q11 = new QuotesList("Life is 10% what happens to us and 90% how we react to it.", "- Charles R. Swindoll");
        lifeQuotesList.add(q11);
        QuotesList q12 = new QuotesList("The harder I work, the luckier I get.", "- Samuel Goldwyn");
        lifeQuotesList.add(q12);
        QuotesList q13 = new QuotesList("Don't watch the clock; do what it does. Keep going.", "- Sam Levenson");
        lifeQuotesList.add(q13);
        QuotesList q14 = new QuotesList("If you want to achieve greatness, stop asking for permission.", "- Anonymous");
        lifeQuotesList.add(q14);
        QuotesList q15 = new QuotesList("Success is not the key to happiness. Happiness is the key to success.", "- Albert Schweitzer");
        lifeQuotesList.add(q15);
        QuotesList q16 = new QuotesList("Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", "- Roy T. Bennett");
        lifeQuotesList.add(q16);
        QuotesList q17 = new QuotesList("Life is about making an impact, not making an income.", "- Kevin Kruse");
        lifeQuotesList.add(q17);
        QuotesList q18 = new QuotesList("The best revenge is massive success.", "- Frank Sinatra");
        lifeQuotesList.add(q18);
        QuotesList q19 = new QuotesList("The biggest risk is not taking any risk.", "- Mark Zuckerberg");
        lifeQuotesList.add(q19);
        QuotesList q20 = new QuotesList("Life is either a daring adventure or nothing at all.", "- Helen Keller");
        lifeQuotesList.add(q20);
        QuotesList q21 = new QuotesList("The secret of getting ahead is getting started.", "- Mark Twain");
        lifeQuotesList.add(q21);
        QuotesList q22 = new QuotesList("The future depends on what you do today.", "- Mahatma Gandhi");
        lifeQuotesList.add(q22);
        QuotesList q23 = new QuotesList("Success usually comes to those who are too busy to be looking for it.", "- Henry David Thoreau");
        lifeQuotesList.add(q23);
        QuotesList q24 = new QuotesList("Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.", "- Steve Jobs");
        lifeQuotesList.add(q24);
        QuotesList q25 = new QuotesList("The only person you are destined to become is the person you decide to be.", "- Ralph Waldo Emerson");
        lifeQuotesList.add(q25);
        QuotesList q26 = new QuotesList("The way to get started is to quit talking and begin doing.", "- Walt Disney");
        lifeQuotesList.add(q26);
        QuotesList q27 = new QuotesList("You miss 100% of the shots you don't take.", "- Wayne Gretzky");
        lifeQuotesList.add(q27);
        QuotesList q28 = new QuotesList("The best revenge is massive success.", "- Frank Sinatra");
        lifeQuotesList.add(q28);
        QuotesList q29 = new QuotesList("Believe you can and you're halfway there.", "- Theodore Roosevelt");
        lifeQuotesList.add(q29);
        QuotesList q30 = new QuotesList("It does not matter how slowly you go as long as you do not stop.", "- Confucius");
        lifeQuotesList.add(q30);
        QuotesList q31 = new QuotesList("If you want to achieve greatness, stop asking for permission.", "- Anonymous");
        lifeQuotesList.add(q31);
        QuotesList q32 = new QuotesList("Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", "- Roy T. Bennett");
        lifeQuotesList.add(q32);
        QuotesList q33 = new QuotesList("Life is about making an impact, not making an income.", "- Kevin Kruse");
        lifeQuotesList.add(q33);
        QuotesList q34 = new QuotesList("The future depends on what you do today.", "- Mahatma Gandhi");
        lifeQuotesList.add(q34);
        QuotesList q35 = new QuotesList("The best way to predict the future is to create it.", "- Peter Drucker");
        lifeQuotesList.add(q35);
        QuotesList q36 = new QuotesList("The only limit to our realization of tomorrow will be our doubts of today.", "- Franklin D. Roosevelt");
        lifeQuotesList.add(q36);
        QuotesList q37 = new QuotesList("Success is not the key to happiness. Happiness is the key to success.", "- Albert Schweitzer");
        lifeQuotesList.add(q37);
        QuotesList q38 = new QuotesList("Don't watch the clock; do what it does. Keep going.", "- Sam Levenson");
        lifeQuotesList.add(q38);
        QuotesList q39 = new QuotesList("The harder I work, the luckier I get.", "- Samuel Goldwyn");
        lifeQuotesList.add(q39);
        QuotesList q40 = new QuotesList("The secret of getting ahead is getting started.", "- Mark Twain");
        lifeQuotesList.add(q40);
        QuotesList q41 = new QuotesList("The only person you are destined to become is the person you decide to be.", "- Ralph Waldo Emerson");
        lifeQuotesList.add(q41);
        QuotesList q42 = new QuotesList("The future belongs to those who believe in the beauty of their dreams.", "- Eleanor Roosevelt");
        lifeQuotesList.add(q42);
        QuotesList q43 = new QuotesList("Your time is limited, don't waste it living someone else's life.", "- Steve Jobs");
        lifeQuotesList.add(q43);
        QuotesList q44 = new QuotesList("The biggest risk is not taking any risk.", "- Mark Zuckerberg");
        lifeQuotesList.add(q44);
        QuotesList q45 = new QuotesList("Success usually comes to those who are too busy to be looking for it.", "- Henry David Thoreau");
        lifeQuotesList.add(q45);
        QuotesList q46 = new QuotesList("Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.", "- Steve Jobs");
        lifeQuotesList.add(q46);
        QuotesList q47 = new QuotesList("You miss 100% of the shots you don't take.", "- Wayne Gretzky");
        lifeQuotesList.add(q47);
        QuotesList q48 = new QuotesList("The only way to do great work is to love what you do.", "- Steve Jobs");
        lifeQuotesList.add(q48);
        QuotesList q49 = new QuotesList("The best revenge is massive success.", "- Frank Sinatra");
        lifeQuotesList.add(q49);
        QuotesList q50 = new QuotesList("Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", "- Roy T. Bennett");
        lifeQuotesList.add(q50);

        Collections.shuffle(lifeQuotesList);
        return lifeQuotesList;
    }
}
